# Google App Engine config file
# -----------------------------
# See https://cloud.google.com/appengine/docs/standard/python3/config/appref

# Recommended to set to Python 3.7 runtime or later
runtime: python311

env_variables:
  CLOUD_SQL_USERNAME: CLOUD_SQL_USERNAME_SECRET
  CLOUD_SQL_PASSWORD: CLOUD_SQL_PASSWORD_SECRET
  CLOUD_SQL_DATABASE_NAME: CLOUD_SQL_DATABASE_NAME_SECRET
  CLOUD_SQL_CONNECTION_NAME: CLOUD_SQL_CONNECTION_NAME_SECRET
  CLOUD_PRIVATE_IP: CLOUD_PRIVATE_IP_SECRET
  PRIVATE_IP: TRUE
# Set App Engine instance class (defaults to F1)
# See https://cloud.google.com/appengine/docs/standard/#instance_classes
instance_class: F1

beta_settings:
  cloud_sql_instances: CLOUD_SQL_INSTANCES_SECRET

vpc_access_connector:
  name: VPS_ACCESS_CONNECTOR_NAME_SECRET

# Set entrypoint to locate FastAPI app, which is 'application' in module app/main.py
# Configure gunicorn worker count via --workers arg based on the App Engine instance class
#   e.g. Set workers = 1 for F1 instance class, workers = 2 for F2, and workers = 4 for F4
# See https://cloud.google.com/appengine/docs/standard/python3/runtime#application_startup
entrypoint: gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind :$PORT src.main:app
