CREATE TABLE USER
(
	Email VARCHAR(255) NOT NULL PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Forename VARCHAR(255) NOT NULL,
	Role INT NOT NULL
);

CREATE TABLE MODEL
(
	Path VARCHAR(255) NOT NULL PRIMARY KEY,
	Date DATE NOT NULL,
	Email VARCHAR(255) FOREIGN KEY REFERENCES USER(Email)
);