CREATE TABLE IF NOT EXISTS USERS(
	Email VARCHAR(255) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Forename VARCHAR(255) NOT NULL,
    password CHAR(255) NOT NULL,
    Cookie VARCHAR(255),
	Role INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MODEL
(
	Path VARCHAR(255) PRIMARY KEY,
	Date TIMESTAMP NOT NULL,
	Email VARCHAR(255) REFERENCES USERS(Email)
);