CREATE TABLE USERS
(
	Email VARCHAR(255) NOT NULL PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Forename VARCHAR(255) NOT NULL,
    Cookie VARCHAR(255),
	Role INT NOT NULL
);

CREATE TABLE MODEL
(
    IdModel SERIAL NOT NULL PRIMARY KEY,
	Path VARCHAR(255) NOT NULL,
	Date DATE NOT NULL,
	Email VARCHAR(255) FOREIGN KEY REFERENCES USER(Email)
);