name: Update GAE Config

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace secrets in YAML file
        run: |
          sed -i 's/\$CLOUD_SQL_USERNAME/\${{ secrets.CLOUD_SQL_USERNAME }}/g' cloud/app.yaml
          sed -i 's/\$CLOUD_SQL_PASSWORD/\${{ secrets.CLOUD_SQL_PASSWORD }}/g' cloud/app.yaml
          sed -i 's/\$CLOUD_SQL_DATABASE_NAME/\${{ secrets.CLOUD_SQL_DATABASE_NAME }}/g' cloud/app.yaml
          sed -i 's/\$CLOUD_SQL_CONNECTION_NAME/\${{ secrets.CLOUD_SQL_CONNECTION_NAME }}/g' cloud/app.yaml
          sed -i 's/\$CLOUD_PRIVATE_IP/\${{ secrets.CLOUD_PRIVATE_IP }}/g' cloud/app.yaml
          sed -i 's/\$CLOUD_SQL_INSTANCES/\${{ secrets.CLOUD_SQL_INSTANCES }}/g' cloud/app.yaml
          sed -i 's/\$VPS_ACCESS_CONNECTOR_NAME/\${{ secrets.VPS_ACCESS_CONNECTOR_NAME }}/g' cloud/app.yaml

      - name: Use updated config
        run: |
          cat cloud/app.yaml
