name: Update GAE Config

on:
    push:
        branches:
            - dev


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Replace secrets in YAML file
              run: |
                perl -pi -e "s/CLOUD_SQL_USERNAME_SECRET/\${{ secrets.CLOUD_SQL_USERNAME }}/g" cloud/app.yaml
                perl -pi -e "s/CLOUD_SQL_PASSWORD_SECRET/\${{ secrets.CLOUD_SQL_PASSWORD }}/g" cloud/app.yaml
                perl -pi -e "s/CLOUD_SQL_DATABASE_NAME_SECRET/\${{ secrets.CLOUD_SQL_DATABASE_NAME }}/g" cloud/app.yaml
                perl -pi -e "s/CLOUD_SQL_CONNECTION_NAME_SECRET/\${{ secrets.CLOUD_SQL_CONNECTION_NAME }}/g" cloud/app.yaml
                perl -pi -e "s/CLOUD_PRIVATE_IP_SECRET/\${{ secrets.CLOUD_PRIVATE_IP }}/g" cloud/app.yaml
                perl -pi -e "s/CLOUD_SQL_INSTANCES_SECRET/\${{ secrets.CLOUD_SQL_INSTANCES }}/g" cloud/app.yaml
                perl -pi -e "s/VPS_ACCESS_CONNECTOR_NAME_SECRET/\${{ secrets.VPS_ACCESS_CONNECTOR_NAME }}/g" cloud/app.yaml

            - name: Use updated config
              run: |
                cat app.yaml
